### ISSUE TITLE
cancel "Merge split views" leaves the purple boxes in the viewer

### ISSUE THREAD

**Issue by luxendo-support** [embl-cba/bigDataProcessor2#78]
When pressing Cancel in the Merge Split Views function, the purple boxes stay visible in the viewer.

**Comment by luxendo-support** [comment]
Forgot the screenshot :)

![BDP2 Merge Split Views cancelled](https://user-images.githubusercontent.com/43034926/77557046-91a90600-6eb9-11ea-9a86-224dfcdaedb4.png)

**Comment by tischi** [comment]
Thanks! This should be fixed now!
