### ISSUE TITLE
SetDisplayRange

### ISSUE THREAD

**Issue by tischi** [embl-cba/bigDataProcessor2#82]
@NicoKiaru 
Hi Nico, I want to change the display settings of just one source in bdv. Below code changes it for **_all_** channels, for reasons that I really do not get ☹️ 
Do you happen to know how I have to adapt this?
```
final List< ConverterSetup > converterSetups = bdvHandle.getSetupAssignments().getConverterSetups();

        final ConverterSetup converterSetup = converterSetups.get( channel );
        converterSetup.setDisplayRange( min, max );

        final MinMaxGroup minMaxGroup =
                getBdvHandle().getSetupAssignments().getMinMaxGroup( converterSetup );

        minMaxGroup.getMinBoundedValue().setCurrentValue( min );
        minMaxGroup.getMaxBoundedValue().setCurrentValue( max );
```
In BDV it looks like this: 
![image](https://user-images.githubusercontent.com/2157566/79203964-198c8b00-7e3c-11ea-94cb-feb05f2274b6.png)
I guess that means the channels are somehow linked? How do I unlink them?

**Comment by NicoKiaru** [comment]
Did you start this window from within the tree in the window or from within a bdv window ?

In the tree you will modify all the children sources of the selected node you've clicked. But if you select a leaf node (= one source), only this one will be modified.

In the bdv window, it's applied on all sources drawn below the mouse when you right-click

**Comment by NicoKiaru** [comment]
Ah, maybe I've missed something. Do you still use the indexing logic ? Because this has disappeared in the new bdv state. Everything now works with maps to which `SourceAndConverter` are keys.

So if you want to change the B&C you have to do something like:
```
SourceAndConverter mySac = ... ;

ConverterSetup cs = bdvh.getConverterSetups().getConverterSetup(mySac);

cs.whateverWithBV(params);
```

But then this works only with the new UI. The legacy one will be broken.

`bdvh.getSetupAssignments()` is deprecated now

**Comment by tischi** [comment]
This is not related to the bdv-playground :-)
This is just good old normal BDV. Do you have an idea? I think probably one has to somehow **_programmatically_** from 

## this mode:

![image](https://user-images.githubusercontent.com/2157566/79211159-24e4b400-7e46-11ea-9209-7b68a05d33a3.png)


## to this mode:
![image](https://user-images.githubusercontent.com/2157566/79211175-2e6e1c00-7e46-11ea-9127-9bc6377bcf45.png)

?!

**Comment by NicoKiaru** [comment]
> This is not related to the bdv-playground :-)
Oups! I did not read on which repo I was 😬 , sorry about that

I guess it's related to these min max groups, like changing minmaxgroups and find a way to update this B&C window? but I've never used minmaxgroup, so I don't think I can have a useful input here.

**Comment by tischi** [comment]
adding this line of code did the trick:

```
setupAssignments.removeSetupFromGroup( converterSetup,  setupAssignments.getMinMaxGroup( converterSetup ) );
```
